# Generated by Django 2.2.4 on 2020-08-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0003_auto_20200818_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='networks',
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(default='...', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
