# Generated by Django 2.2.4 on 2020-08-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_show_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='shows',
        ),
        migrations.AddField(
            model_name='show',
            name='networks',
            field=models.ManyToManyField(related_name='networks', to='tv_shows.Network'),
        ),
    ]
